-- Socials on leads + generated proposal package on deals.
-- Idempotent (where possible). ALTER COLUMN errors on re-run; ignore.
--
-- Apply with:
--   wrangler d1 execute pymewebpro-portal --remote --file=migrations/0005_socials_and_proposals.sql

-- 1. Extra social URL fields on leads. The existing `instagram` column stays
-- as the Instagram handle or URL (whatever the user typed). These three are
-- new dedicated URL slots so each card has Facebook, X (Twitter), TikTok.
ALTER TABLE leads ADD COLUMN facebook_url TEXT;
ALTER TABLE leads ADD COLUMN x_url        TEXT;
ALTER TABLE leads ADD COLUMN tiktok_url   TEXT;

-- 2. Generated proposal package on deals.
--   proposal_mockup_html  · single-file self-contained marketing mockup HTML
--                           generated by Anthropic from the linked lead's
--                           social profiles and notes. Served at
--                           /proposal-mockup/<deal-id>.
--   proposal_html         · the printable proposal page (mockup iframe +
--                           pricing + benefits + terms). Served at
--                           /admin/proposal/<deal-id>.
--   proposal_generated_at · ms timestamp of the last generation.
--   proposal_status       · 'pending' | 'generating' | 'ready' | 'error'.
ALTER TABLE deals ADD COLUMN proposal_mockup_html  TEXT;
ALTER TABLE deals ADD COLUMN proposal_html         TEXT;
ALTER TABLE deals ADD COLUMN proposal_generated_at INTEGER;
ALTER TABLE deals ADD COLUMN proposal_status       TEXT;
