// tools.js · Valentina's tool catalog.
// Schema follows Anthropic's tool-use format: name, description, input_schema.
//
// Valentina does NOT take payment. Her close is: capture the contact, then
// book a call with Santi. Payment links are generated by Mike and shared by
// Santi via WhatsApp after the call (decision 2026-05-25). The Wompi
// deposit-link tool was removed; payments.js stays in the repo unused in case
// we ever wire self-serve checkout back in.

import { sendWhatsAppText } from "./whatsapp.js";
import { updateConversationContact } from "./db.js";
import { listSlots, bookSlot, pickReadableSlots } from "./scheduling.js";

export const TOOLS = [
  {
    name: "capture_contact",
    description: "Save the prospect's contact details. Call this EARLY, as soon as you have their name, phone (WhatsApp), and email · BEFORE offering call slots. Safe to call again to update/add a field. Stores the details on the conversation so Santi can follow up.",
    input_schema: {
      type: "object",
      properties: {
        contact_name: { type: "string", description: "Prospect's full name." },
        phone: { type: "string", description: "Prospect's WhatsApp / phone with country code, e.g. +57 3xx xxx xxxx." },
        contact_email: { type: "string", description: "Prospect's email." },
        business_name: { type: "string", description: "Optional. Prospect's business / company name." }
      },
      required: ["contact_name", "phone", "contact_email"]
    },
  },
  {
    name: "send_plan_brief",
    description: "Return a short Spanish summary of the product (the $400.000 COP base sales page, what's included, timeline, and the optional all-in monthly plan), so Valentina can paste the key facts into the conversation. Use when the prospect asks what's included or what it costs. There is ONE product; the monthly plan is optional.",
    input_schema: {
      type: "object",
      properties: {},
      required: []
    }
  },
  {
    name: "list_call_slots",
    description: "Pull 3-5 real open 15-minute slots from Santi's Google Calendar over the next ~5 business days. Santi does the PymeWebPro calls. This is the main close: once you have the contact details, offer call slots. Present the slots in the prospect's timezone. Call this BEFORE book_call. If it returns not_configured, fall back to escalate_to_human.",
    input_schema: {
      type: "object",
      properties: {
        timezone: { type: "string", description: "Prospect's IANA timezone, e.g. 'America/Bogota', 'America/New_York'. Defaults to America/Bogota." },
        days_ahead: { type: "number", description: "Days ahead to search (1-14, default 7)." }
      },
      required: []
    }
  },
  {
    name: "book_call",
    description: "Book a 15-minute call with Santi at a specific time. Creates the event on Santi's Google Calendar, adds the prospect as attendee, auto-generates a Google Meet link, and Google emails everyone the invite. Pass the exact ISO datetime from list_call_slots plus the prospect's name and email. Confirm name + email + time in plain text before calling.",
    input_schema: {
      type: "object",
      properties: {
        slot_iso: { type: "string", description: "Exact ISO datetime from a list_call_slots result." },
        name: { type: "string", description: "Prospect's name." },
        email: { type: "string", description: "Prospect's email (gets the calendar invite)." },
        timezone: { type: "string", description: "Prospect's IANA timezone. Defaults to America/Bogota." },
        note: { type: "string", description: "Optional one-line context for Santi." }
      },
      required: ["slot_iso", "email"]
    }
  },
  {
    name: "escalate_to_human",
    description: "Ping Mike (default) or Santi on their personal WhatsApp with a summary of this conversation and a link to the agent inbox. Use when: (1) the prospect explicitly asks for a human outside a scheduled call, (2) you can't answer a substantive question after one try, (3) the prospect is clearly a custom-scope lead (real store, blog, app) that doesn't fit the sales page. Default target is 'mike' for English conversations, 'santi' for Spanish conversations.",
    input_schema: {
      type: "object",
      properties: {
        reason: { type: "string", description: "One sentence: why this is being escalated." },
        summary: { type: "string", description: "2-3 sentence recap of the conversation so far. Include the prospect's name, business, and what they're asking for." },
        target: { type: "string", enum: ["mike", "santi"], description: "Who to ping. Default: mike for EN, santi for ES." }
      },
      required: ["reason", "summary"]
    }
  },
  {
    name: "start_mockup",
    description: "Create a free, no-commitment mockup for an interested prospect and get a private intake-wizard link to send them. Call this once you have their business name and a way to reach them, and they want to see a sample of their page. It adds them to the team board in the 'mockup' stage and returns a link to a short Spanish wizard where they upload their logo, a few photos, and their vision. Send them that EXACT link and say it is optional but makes the mockup come out much better. No payment and no commitment. Prefer this over capture_contact for prospects who want a mockup.",
    input_schema: {
      type: "object",
      properties: {
        business_name: { type: "string", description: "Prospect's business name." },
        contact_name: { type: "string", description: "Prospect's name." },
        phone: { type: "string", description: "WhatsApp / phone with country code." },
        contact_email: { type: "string", description: "Email (optional if phone is given)." },
        city: { type: "string", description: "City or service area (optional)." },
        message: { type: "string", description: "Optional: what they want or any context." }
      },
      required: ["business_name"]
    }
  },
];

// ---------------------------------------------------------------------------
// Tool executors
// ---------------------------------------------------------------------------

function planBrief() {
  return {
    ok: true,
    plan: "pagina",
    label: "La página de ventas",
    price_cop: 400_000,
    brief_es:
      "La página de ventas · $400.000 COP, IVA incluido. Una página de ventas de alta conversión en 6 pasos, hecha a la medida sin plantilla, lista en 48 horas. Incluye: tu Ficha de Google configurada para que te encuentren en el mapa, optimizada para móvil, botón click-para-llamar + WhatsApp, formulario de contacto, sección de testimonios, integración de reservas/citas (Cal.com, Calendly), configuración SEO sólida (schema, meta, sitemap), conexión de dominio + SSL (el dominio va por cuenta del cliente, lo ayudamos a conseguirlo), embed de Google Maps, analíticas privacy-first, 1 mes de hosting y soporte, y 2 rondas de ajustes. Cómo funciona: primero ves tu página (te armamos una muestra real de tu negocio). Cuando estés contento, pagas el total ($400.000 COP) y la publicamos. Sin depósito y sin compromiso por adelantado. Pago en COP via Wompi (tarjetas, PSE, transferencia). Garantía de devolución a 30 días." +
      "Plan mensual opcional (después del mes incluido, sin contrato): Plan mensual $150.000 COP/mes, todo incluido (hosting + Ficha de Google activa y actualizada + versión bilingüe ES/EN + soporte por WhatsApp + hasta 2 cambios al mes + asistente de ventas 24/7: un chatbot en tu página que conoce tu negocio, responde las preguntas, pasa al cliente a tu WhatsApp y agenda llamadas + vitrina de hasta 30 productos + catálogo o menú descargable + reporte mensual con la actividad de tus clientes). El primer mes va incluido con la página. " +
      "Tienda real y blog se cotizan aparte.",
    brief_en:
      "The sales page · $400.000 COP, VAT included. One high-conversion 6-step sales page, custom built (no templates), live in 48 hours. Includes: your Google Business Profile set up so customers find you on the map, mobile-optimized, click-to-call + WhatsApp button, contact form, testimonials section, booking/appointment integration (Cal.com, Calendly), solid SEO config (schema, meta, sitemap), domain + SSL setup (the domain itself is the client's cost, we help them get one), Google Maps embed, privacy-first analytics, 1 month of hosting + support, and 2 revision rounds. How it works: you see your page first (we build you a real sample of your business). When you are happy, you pay in full ($400.000 COP) and we publish it. No deposit and no upfront commitment. Payment in COP via Wompi (cards, PSE, bank transfer). 30-day money-back guarantee." +
      "Optional monthly plan (after the included month, no contract): Plan mensual $150.000 COP/mo, all included (hosting + active, updated Google Business Profile + bilingual ES/EN version + WhatsApp support + up to 2 changes a month + a 24/7 sales assistant: a chatbot on your page that knows your business, answers questions, sends the customer to your WhatsApp and books calls + a showcase of up to 30 products + a downloadable catalog or menu + a monthly report on your customer activity). The first month is included with the page. " +
      "A real store and a blog are quoted separately.",
  };
}

async function runCaptureContact(input, ctx) {
  const { db, conversationId } = ctx;
  const { contact_name, phone, contact_email, business_name } = input;
  if (!contact_name || !phone || !contact_email) {
    return { ok: false, error: "missing required field (contact_name / phone / contact_email)" };
  }
  await updateConversationContact(db, conversationId, {
    contact_name,
    contact_phone: phone,
    contact_email,
    business_name: business_name || null,
  });
  return { ok: true, captured: { contact_name, phone, contact_email, business_name: business_name || null } };
}

async function runListCallSlots(input, ctx) {
  const { env } = ctx;
  const host = "santi"; // PymeWebPro calls are done by Santi
  const tz = input.timezone || "America/Bogota";
  const days = Math.min(Math.max(Number(input.days_ahead || 7), 1), 14);
  const startISO = new Date(Date.now() + 60 * 60 * 1000).toISOString();
  const endISO = new Date(Date.now() + days * 86400000).toISOString();
  const slotsByDate = await listSlots(env, { host, startISO, endISO, daysAhead: days, timeZone: tz });
  if (!slotsByDate) {
    return { ok: false, error: "not_configured", note: "Google Calendar isn't connected for that host. Use escalate_to_human instead." };
  }
  const picked = pickReadableSlots(slotsByDate, { tz, limit: 5 });
  if (!picked.length) {
    return { ok: true, host, slots: [], message: `No open slots in the next ${days} days for ${host}. Offer the other host, extend days_ahead, or escalate.` };
  }
  return {
    ok: true,
    host,
    slots: picked,
    message: `Present these ${host === "mike" ? "Mike" : "Santi"} slots in the prospect's timezone. When they pick one, confirm their name + email, then call book_call with host='${host}' and that slot's iso value.`,
  };
}

async function runBookCall(input, ctx) {
  const { env } = ctx;
  const host = "santi"; // PymeWebPro calls are done by Santi
  if (!input.slot_iso || !input.email) {
    return { ok: false, error: "need both slot_iso and email" };
  }
  const tz = input.timezone || "America/Bogota";
  const r = await bookSlot(env, {
    host,
    startISO: input.slot_iso,
    name: input.name || "Guest",
    email: input.email,
    timeZone: tz,
    note: input.note,
  });
  if (!r.ok) {
    if (r.reason === "not_configured") return { ok: false, error: "Google Calendar not connected. Fall back to escalate_to_human." };
    return { ok: false, error: r.reason || "Booking failed. Try a different slot or escalate." };
  }
  return {
    ok: true,
    host,
    meet_link: r.booking.hangoutLink,
    event_link: r.booking.htmlLink,
    when: input.slot_iso,
    note_en: "Booked. You'll get a Google Calendar invite by email with the Google Meet link.",
    note_es: "Listo, reservado. Te llega la invitación de Google Calendar con el link de Google Meet.",
  };
}

async function runEscalateToHuman(input, ctx) {
  const { env, db, conversationId } = ctx;
  const { reason, summary, target } = input;

  // Load conversation context for the WA ping.
  const conv = await db.prepare(`SELECT * FROM conversations WHERE id = ?`).bind(conversationId).first();
  const lang = conv?.language || "es";
  const finalTarget = target || (lang === "en" ? "mike" : "santi");
  const wa = finalTarget === "mike" ? env.MIKE_WA_NUMBER : env.SANTI_WA_NUMBER;

  const lead = conv?.contact_name
    ? `${conv.contact_name}${conv.business_name ? ` (${conv.business_name})` : ""}`
    : "(name not captured)";
  const channel = conv?.channel === "whatsapp"
    ? `WhatsApp ${conv.contact_phone || ""}`
    : "web chat";
  const inboxLink = `https://valentina.pymewebpro.com/inbox/conv/${conversationId}`;

  const body = [
    `Valentina escalation · ${finalTarget}`,
    `Channel: ${channel}`,
    `Prospect: ${lead}`,
    `Reason: ${reason}`,
    "",
    summary,
    "",
    inboxLink,
  ].join("\n");

  const sendResult = await sendWhatsAppText(env, wa, body);

  // Mark conversation as escalated.
  await db.prepare(
    `UPDATE conversations SET status = 'escalated', updated_at = ? WHERE id = ?`
  ).bind(Date.now(), conversationId).run();

  return {
    ok: !!sendResult.ok,
    target: finalTarget,
    wa_send: sendResult.ok,
    note_for_user_es: `Listo, le pasé el mensaje a ${finalTarget === "mike" ? "Mike" : "Santi"}. Te escribe directo a este chat o por WhatsApp en breve.`,
    note_for_user_en: `Done, I just pinged ${finalTarget === "mike" ? "Mike" : "Santi"}. They'll reach back here or on WhatsApp shortly.`,
  };
}

async function runStartMockup(input, ctx) {
  const { env, db, conversationId } = ctx;
  const portal = env.PORTAL_DB;
  if (!portal) return { ok: false, error: "portal db not bound", fallback: "use capture_contact" };

  const leadId = crypto.randomUUID();
  const token = crypto.randomUUID().replace(/-/g, "");
  const now = Date.now();
  let language = "es";
  try {
    const conv = await db.prepare("SELECT language FROM conversations WHERE id = ?").bind(conversationId).first();
    if (conv && conv.language) language = conv.language;
  } catch {}

  const metadata = JSON.stringify({ source: "valentina-agent", conversation_id: conversationId, mockup_mode: true, city: input.city || null });
  try {
    await portal.prepare(
      `INSERT INTO leads (id, source, name, email, phone, business_name, message, language, status, lead_stage, plan, hosting, metadata, wizard_token, created_at, updated_at)
       VALUES (?, 'valentina-agent', ?, ?, ?, ?, ?, ?, 'new', 'mockup', 'esencial', 'none', ?, ?, ?, ?)`
    ).bind(
      leadId,
      input.contact_name || null,
      input.contact_email || null,
      input.phone || null,
      input.business_name || null,
      `Mockup iniciado por Valentina. ${input.message || ""}`.trim(),
      language,
      metadata,
      token,
      now, now,
    ).run();
  } catch (e) {
    console.error("start_mockup insert failed", e);
    return { ok: false, error: "no se pudo crear el lead", fallback: "use capture_contact" };
  }

  const link = `https://valentina.pymewebpro.com/w/${token}`;
  // Ping Santi so the team sees the new mockup lead on the board.
  try {
    await sendWhatsAppText(env, env.SANTI_WA_NUMBER,
      `Nuevo mockup (Valentina): ${input.business_name || input.contact_name || "(sin nombre)"}\nWizard: ${link}\nLead: ${leadId}`);
  } catch {}

  return {
    ok: true,
    wizard_link: link,
    note_for_user_es: `Listo, ya empecé tu muestra gratis. Para que quede a tu medida, abre este enlace y sube tu logo, unas fotos y cuéntanos tu visión (unos minutos, es opcional pero mejora mucho el resultado): ${link}`,
    note_for_user_en: `Done, I started your free mockup. To make it yours, open this link to add your logo, a few photos, and your vision (a few minutes, optional but it makes the result much better): ${link}`,
  };
}

export async function runTool(name, input, ctx) {
  try {
    let result;
    if (name === "capture_contact") result = await runCaptureContact(input, ctx);
    else if (name === "send_plan_brief") result = planBrief();
    else if (name === "list_call_slots") result = await runListCallSlots(input, ctx);
    else if (name === "book_call") result = await runBookCall(input, ctx);
    else if (name === "escalate_to_human") result = await runEscalateToHuman(input, ctx);
    else if (name === "start_mockup") result = await runStartMockup(input, ctx);
    else result = { ok: false, error: `Unknown tool: ${name}` };
    return JSON.stringify(result);
  } catch (e) {
    console.error(`tool ${name} threw:`, e);
    return JSON.stringify({ ok: false, error: String(e?.message || e) });
  }
}
