-- Seed: 15 verified Medellin health/aesthetic clinic prospects (beachhead batch 1).
-- Researched + verified 2026-05-24. Phones/WhatsApp are intentionally NULL: enrich
-- via the Google Places prospecting tool to get accurate contact numbers before
-- outreach. suggested_pitch holds the real, observed weakness so the AI drafter
-- (/api/admin/outreach/draft) personalizes the first message.
--
-- Idempotent (INSERT OR IGNORE on a stable id). Safe to re-run.
-- Run: cd ~/code/pymewebpro/portal && wrangler d1 execute pymewebpro-portal --remote --file=seeds/2026-05-24-medellin-clinics.sql

INSERT OR IGNORE INTO leads (id, source, business_name, language, status, lead_stage, category, city, address, current_site, instagram, motion, suggested_pitch, on_today_list, touches_count, created_at, updated_at) VALUES
('seed-mde-clinic-01','outbound','Deluxe Smile','es','new','new','odontologia','Medellin','Sabaneta','https://www.deluxe-smile.com/','deluxesmile.co','upgrade','Los botones de Contactanos apuntan a un archivo local roto, el sitio no captura ningun lead pese a tener trafico.',0,0,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('seed-mde-clinic-02','outbound','Odontorisas','es','new','new','odontologia','Medellin','Belen','https://odontorisas.com/','odontorisas_','upgrade','Imagenes en blanco, contadores de pacientes en 0, y texto de plantilla sin editar: se ve sin terminar y poco confiable.',0,0,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('seed-mde-clinic-03','outbound','Oral 10 Odontologia','es','new','new','odontologia','Medellin','El Poblado','https://oral10odontologia.com/','oral10odontologia','upgrade','Tiene texto Lorem ipsum y un equipo y direccion de Estados Unidos falsos, todo de plantilla, sobre un negocio real y activo.',0,0,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('seed-mde-clinic-04','outbound','Shine Odontologia','es','new','new','odontologia','Medellin','Belen','https://www.shineodontologia.co/','shineodontologia.co','upgrade','El sitio es una pagina de Google Sites sin marca propia, titulo generico Pagina principal.',0,0,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('seed-mde-clinic-05','outbound','Fisiocinetics','es','new','new','fisioterapia','Medellin','Belen','https://fisiocinetics.com/',NULL,'upgrade','Todos los botones Agenda tu cita apuntan a un enlace de WhatsApp invalido, la via de conversion no funciona en todo el sitio.',0,0,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('seed-mde-clinic-06','outbound','Centro Medico Coromoto','es','new','new','dermatologia','Medellin','Laureles','https://www.centromedicocoromoto.com/dermatologia/','consultoriosvirgencoromoto','upgrade','Pagina de plantilla generica con geoetiquetas apuntando a Bogota y un enlace de menu roto.',0,0,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('seed-mde-clinic-07','outbound','Odontoss','es','new','new','odontologia','Medellin','Laureles','https://www.odontoss.com/','clinica_odontoss','upgrade','Tiene un enlace de spam de apuestas inyectado en el footer (sitio comprometido), señal de un WordPress descuidado.',0,0,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('seed-mde-clinic-08','outbound','ProSmile Odontologia','es','new','new','odontologia','Medellin','Belen','https://prosmileodontologia.com/','prosmileodontologia','upgrade','El header muestra un telefono placeholder con codigo de area canadiense y enlaces sociales muertos.',0,0,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('seed-mde-clinic-09','outbound','Nueva Piel Spa','es','new','new','estetica','Medellin','Laureles','https://nuevapielspa.com/','nuevapielspa','upgrade','El mapa de ubicacion carga en blanco, varios iconos de contacto estan muertos y el logo aparece vacio.',0,0,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('seed-mde-clinic-10','outbound','Estetica y Belleza IPS','es','new','new','estetica','Medellin','Laureles','https://esteticaybellezamedellin.com/','esteticaybellezaips','upgrade','La seccion de preguntas frecuentes no muestra respuestas y los enlaces del footer estan rotos.',0,0,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('seed-mde-clinic-11','outbound','La Piel Spa','es','new','new','estetica','Medellin',NULL,'https://www.lapielspa.com/',NULL,'upgrade','El sitio carga en blanco sin contenido visible, probablemente roto, lo que equivale a no tener presencia web.',0,0,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('seed-mde-clinic-12','outbound','LR Clinica Odontologica','es','new','new','odontologia','Medellin','Laureles','https://lrclinicaodontologica.com/',NULL,'upgrade','El sitio carga en blanco; es una clinica de implantes (alto ticket) sin presencia web funcional.',0,0,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('seed-mde-clinic-13','outbound','All Smiles Odontologia','es','new','new','odontologia','Medellin','Sabaneta',NULL,'allsmilesodontologia','new_build','Sin sitio web, solo Instagram: pierde a los clientes que la buscan en Google.',0,0,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('seed-mde-clinic-14','outbound','Dental Clinic Soluciones','es','new','new','odontologia','Medellin','Sabaneta',NULL,'dentalclinicsoluciones','new_build','Cerca de 5.800 seguidores en Instagram y ningun sitio propio para convertir esa audiencia.',0,0,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('seed-mde-clinic-15','outbound','Tooth Dentistry','es','new','new','odontologia','Medellin','Sabaneta',NULL,'tooth.dentistry','new_build','Solo Instagram, sin sitio: una pagina de ventas con boton de WhatsApp capturaria ese trafico.',0,0,(strftime('%s','now')*1000),(strftime('%s','now')*1000));
